from Item import Item

PC = Item()
PC.setID("ROG123")
PC.setPrice(35000000)
PC.setBrand("NVIDIA")
PC.setModel("RTX 3090")
PC.setFreq(1500)
PC.setMemSize(24)
PC.setCuda(True)

PC2 = Item()
PC2.setID("MSI123")
PC2.setPrice(15000000)
PC2.setBrand("AMD")
PC2.setModel("RX 6700 XT")
PC2.setFreq(2600)
PC2.setMemSize(12)
PC2.setCuda(False)

print('===============================')
print("ID           : "+str(PC.getID()))
print("Harga        : "+str(PC.getPrice()))
print("Brand        : "+str(PC.getBrand()))
print("Model        : "+str(PC.getModel()))
print("Frequency    : "+str(PC.getFreq()))
print("VRAM Size    : "+str(PC.getMemSize()))
print("Cuda Support : "+str(PC.getCuda()))
print('===============================')
print("ID           : "+str(PC2.getID()))
print("Harga        : "+str(PC2.getPrice()))
print("Brand        : "+str(PC2.getBrand()))
print("Model        : "+str(PC2.getModel()))
print("Frequency    : "+str(PC2.getFreq()))
print("VRAM Size    : "+str(PC2.getMemSize()))
print("Cuda Support : "+str(PC2.getCuda()))
print('===============================')

